#!/bin/bash
sudo touch tempExec
sudo echo "nohup java -jar /opt/ccp/xservice/test10000-0.0.1-SNAPSHOT.jar >/dev/null >/dev/null 2>&1 & disown" >> tempExec
sudo chmod +x tempExec
sudo nohup ./tempExec
echo all well
